exec = require('child_process').exec
fs = require 'fs'
coffekup = require 'coffeekup'

task 'build', ->
  fs.readFile 'template.coffee', 'utf-8', (err, data) ->
    puts err if err
    compiled = coffekup.compile data
    str = String(compiled).replace 'function anonymous', 'function template'
    fs.writeFile 'template.js', str, (err) ->
      puts err if err
